### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by jingsam** [olanod/mapbox-gl-js-bower#2]
It appears the directory of font is still missing when I install mapbox-gl-js with "bower install mapbox-gl-js"

**Comment by jingsam** [comment]
It seems that the latest release v0.8.1 should be deleted and recreate one

**Comment by olanod** [comment]
yes, my bad. I have to create a new tag

**Comment by olanod** [comment]
I updated the tag to point to the last commit. Since its the same tag as before you might need to clean bower's cache (`bower cache clean`) and install again.
